apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namePrefix: demo-project-prod-
patches:
- target:
    kind: Deployment
    name: aws-load-balancer-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/0
      value: --cluster-name=demo-project-prod-eks
- target:
    kind: Ingress
    name: grafana
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: grafana.demo-project-prod.example.com
