apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namePrefix: demo-project-prod-
patches:
- target:
    kind: Deployment
    name: aws-load-balancer-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/0
      value: --cluster-name=demo-project-dev-eks
- target:
    kind: Ingress
    name: grafana
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: grafana.demo-project-dev.example.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: grafana.demo-project-dev.example.com
# Use staging issuer for dev environment to avoid rate limits
- target:
    kind: Certificate
    name: grafana-tls
  patch: |-
    - op: replace
      path: /spec/issuerRef/name
      value: letsencrypt-staging
    - op: replace
      path: /spec/dnsNames/0
      value: grafana.demo-project-dev.example.com
